name: Mobile-RDP
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Connect Tailscale
      uses: tailscale/github-action@v2
      with:
        authkey: ${{ secrets.TAILSCALE_AUTH_KEY }}
    - name: Setup Password
      run: |
        net user runneradmin "${{ secrets.RDP_PASSWORD }}"
    - name: Keep Alive
      run: |
        while ($true) { Start-Sleep -Seconds 60 }
